SELECT
  cc.CONTACT_CODE,
  ct.GIVEN_NAME,
  ct.SURNAME,
  ct.E_MAIL_ADDRESS,
  COUNT(DISTINCT cc.COMPANY_CODE) AS company_cnt
FROM stg_cts_company_contact cc
JOIN stg_cts_contact ct ON ct.CONTACT_CODE = cc.CONTACT_CODE
GROUP BY cc.CONTACT_CODE, ct.GIVEN_NAME, ct.SURNAME, ct.E_MAIL_ADDRESS
HAVING COUNT(DISTINCT cc.COMPANY_CODE) >= 5
ORDER BY company_cnt DESC
LIMIT 50;
